/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import javax.swing.JOptionPane;
import Controllers.StudyGroups3Controller;
import java.util.ArrayList;

/**
 *
 * @author Atmani
 */
public class StudyGroups3 extends javax.swing.JFrame { //StudyGroups3 extends JFrame in order to use its GUI functionalities.

    private StudyGroups3Controller controller = new StudyGroups3Controller(); //Instance of the "StudyGroups3Controller" controller class. 
    //Allows using functions of the "StudyGroups3Controller" class inside the "StudyGroups3" class. 

    /**
     * Creates new form StudyGroups3
     */
    private String UserName;

    public StudyGroups3(String UN1) { //Constructor of the "StudyGroups3" GUI class.
        UserName = UN1;
        initComponents();

        ArrayList<String> rs = controller.GroupSubjects(UN1);

        jComboBox3.addItem("");
        jComboBox2.addItem("");

        for (String x : rs) {
            if (!x.equals("")) {
                jComboBox1.addItem(x); //Adds the subjects of the user to the "jComboBox1".
                jComboBox3.addItem(x); //Adds the subjects of the user to the "jComboBox3".
                jComboBox2.addItem(x); //Adds the subjects of the user to the "jComboBox2".

            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        KeyTopic1 = new javax.swing.JTextField();
        KeyTopic2 = new javax.swing.JTextField();
        KeyTopic3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        FromTime = new javax.swing.JTextField();
        ToTime = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Rooms = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(135, 176, 209));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Create Groups");

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jButton2.setText("⬅");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Subject/s:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Subject 1:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Subject 2 (Optional):");

        jComboBox1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusedBorderColor"));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Required" }));
        jComboBox1.setToolTipText("");

        jComboBox2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusedBorderColor"));

        jComboBox3.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusedBorderColor"));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Time laps:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("Subject 3 (Optional):");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setText("Topic/s:");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setText("Key Topic 1:");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel11.setText("Key Topic 2 (Optional):");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel12.setText("Key Topic 3 (Optional):");

        KeyTopic1.setBackground(new java.awt.Color(204, 204, 204));
        KeyTopic1.setForeground(new java.awt.Color(102, 102, 102));
        KeyTopic1.setText("Thermodynamics");
        KeyTopic1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KeyTopic1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KeyTopic1FocusLost(evt);
            }
        });

        KeyTopic2.setBackground(new java.awt.Color(204, 204, 204));
        KeyTopic2.setForeground(new java.awt.Color(102, 102, 102));
        KeyTopic2.setText("Organic Chem");
        KeyTopic2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KeyTopic2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KeyTopic2FocusLost(evt);
            }
        });

        KeyTopic3.setBackground(new java.awt.Color(204, 204, 204));
        KeyTopic3.setForeground(new java.awt.Color(102, 102, 102));
        KeyTopic3.setText("For Loops");
        KeyTopic3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KeyTopic3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KeyTopic3FocusLost(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton1.setText("Create Group");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        FromTime.setBackground(new java.awt.Color(204, 204, 204));
        FromTime.setForeground(new java.awt.Color(102, 102, 102));
        FromTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FromTime.setText("7");
        FromTime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FromTimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FromTimeFocusLost(evt);
            }
        });

        ToTime.setBackground(new java.awt.Color(204, 204, 204));
        ToTime.setForeground(new java.awt.Color(102, 102, 102));
        ToTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ToTime.setText("15");
        ToTime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ToTimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ToTimeFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setText("Clases:");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel14.setText("Room:");

        Rooms.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusedBorderColor"));
        Rooms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room 1 Sb", "Room 2 Sb", "Room 3 Sb", "Room 4 Sb", "Room 4/3 Sb", "Room 5 Sb", "Room 6 Sb", "Room 7 Sb", "Room ESS St", "Room Lab St", "Room Arts St", "Room Teachers St", "Room AC St", "Room GP St" }));

        jPanel2.setBackground(new java.awt.Color(135, 176, 209));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Starting hour      To        Ending time");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Pm/Am System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KeyTopic1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KeyTopic2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KeyTopic3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5))
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FromTime, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(ToTime, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(KeyTopic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(KeyTopic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(KeyTopic3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Rooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KeyTopic1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KeyTopic1FocusGained
        // TODO add your handling code here:
        if (KeyTopic1.getText().equals("Thermodynamics")) {
            KeyTopic1.setText("");
            KeyTopic1.setForeground(Color.black);
        }
    }//GEN-LAST:event_KeyTopic1FocusGained

    private void KeyTopic1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KeyTopic1FocusLost
        // TODO add your handling code here:
        if (KeyTopic1.getText().equals("")) {
            KeyTopic1.setText("Thermodynamics");
            KeyTopic1.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_KeyTopic1FocusLost

    private void KeyTopic2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KeyTopic2FocusGained
        // TODO add your handling code here:
        if (KeyTopic2.getText().equals("Organic Chem")) {
            KeyTopic2.setText("");
            KeyTopic2.setForeground(Color.black);
        }
    }//GEN-LAST:event_KeyTopic2FocusGained

    private void KeyTopic2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KeyTopic2FocusLost
        // TODO add your handling code here:
        if (KeyTopic2.getText().equals("")) {
            KeyTopic2.setText("Organic Chem");
            KeyTopic2.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_KeyTopic2FocusLost

    private void KeyTopic3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KeyTopic3FocusGained
        // TODO add your handling code here:
        if (KeyTopic3.getText().equals("For Loops")) {
            KeyTopic3.setText("");
            KeyTopic3.setForeground(Color.black);
        }
    }//GEN-LAST:event_KeyTopic3FocusGained

    private void KeyTopic3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KeyTopic3FocusLost
        // TODO add your handling code here:
        if (KeyTopic3.getText().equals("")) {
            KeyTopic3.setText("For Loops");
            KeyTopic3.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_KeyTopic3FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Subject1 = jComboBox1.getSelectedItem().toString(); //Obtain the "Subject1" subject from the "jComboBox1".
        String Subject2 = jComboBox2.getSelectedItem().toString(); //Obtain the "Subject2" subject from the "jComboBox2".
        String Subject3 = jComboBox3.getSelectedItem().toString(); //Obtain the "Subject3" subject from the "jComboBox3".

        String Topic1 = KeyTopic1.getText(); //Obtain the "Topic1" from the text field "KeyTopic1".
        String Topic2 = KeyTopic2.getText(); //Obtain the "Topic2" from the text field "KeyTopic2".
        String Topic3 = KeyTopic3.getText(); //Obtain the "Topic3" from the text field "KeyTopic3".

        if (Subject2.equals("")) {
            Subject2 = "null";
        }

        if (Subject3.equals("")) {
            Subject3 = "null";
        }

        if (Topic1.equals("Thermodynamics")) {
            Topic1 = "";
        }

        if (Topic2.equals("Organic Chem")) {
            Topic2 = "";
        }

        if (Topic3.equals("For Loops")) {
            Topic3 = "";
        }

        int FromT = Integer.parseInt(FromTime.getText()); //String to Int.
        int ToT = Integer.parseInt(ToTime.getText()); //String to Int.

        String Room = Rooms.getSelectedItem().toString(); //Obtain the "Room" Room from the jComboBox "Rooms".

        //https://stackoverflow.com/questions/14169240/getting-integer-values-from-textfield
        controller.insertNewGroup(UserName, Subject1, Subject2, Subject3, Topic1, Topic2, Topic3, Room, FromT, ToT); //To Add a new StudyGroup.
        controller.updateGroupStatus(UserName, 1, UserName); //Update group status. Thanks to this the program will know that the user is already in a group.
        controller.EmailsToSendNotificationsV2(Subject1, Subject2, Subject3); //Inform certain users by email that a new StudyGroup has been created.

        //Move to the "StudyGroups4" GUI class:
        StudyGroups4 x = new StudyGroups4(UserName, Subject1, Subject2, Subject3, Topic1, Topic2, Topic3, Room, FromT, ToT);
        this.hide();
        x.setVisible(true);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void ToTimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ToTimeFocusLost
        // TODO add your handling code here:
        if (KeyTopic3.getText().equals("")) {
            KeyTopic3.setText("15");
            KeyTopic3.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_ToTimeFocusLost

    private void ToTimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ToTimeFocusGained
        // TODO add your handling code here:
        if (KeyTopic3.getText().equals(15)) {
            KeyTopic3.setText("");
            KeyTopic3.setForeground(Color.black);
        }
    }//GEN-LAST:event_ToTimeFocusGained

    private void FromTimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FromTimeFocusLost
        // TODO add your handling code here:
        if (KeyTopic3.getText().equals("")) {
            KeyTopic3.setText("7");
            KeyTopic3.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_FromTimeFocusLost

    private void FromTimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FromTimeFocusGained
        // TODO add your handling code here:
        if (KeyTopic3.getText().equals(7)) {
            KeyTopic3.setText("");
            KeyTopic3.setForeground(Color.black);
        }
    }//GEN-LAST:event_FromTimeFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        StudyGroups1 x = new StudyGroups1(UserName);
        this.hide();
        x.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FromTime;
    private javax.swing.JTextField KeyTopic1;
    private javax.swing.JTextField KeyTopic2;
    private javax.swing.JTextField KeyTopic3;
    private javax.swing.JComboBox<String> Rooms;
    private javax.swing.JTextField ToTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
