/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Controllers.Tutoring1Controller;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Atmani
 */
public class Tutoring1 extends javax.swing.JFrame { //Tutoring1 extends JFrame in order to use its GUI functionalities.
    
    private Tutoring1Controller controller = new Tutoring1Controller(); //Instance of the "Tutoring1Controller" controller class. 
    //Allows using functions of the "Tutoring1Controller" class inside the "Tutoring1" class. 

    /**
     * Creates new form Tutoring
     */
    
    private String UserName;
    
    //Constructor of the "Tutoring1" GUI class:
    public Tutoring1(String UN) { // Receival of the "UserName" parameter.
        initComponents();
        UserName = UN;
        ArrayList<String> rs = controller.AllTutoring();
         JList list = new JList(rs.toArray()); // Create Jlist with name "list".
         // Set the values of the GUI element "jList1" to the values of "list":
         jList1.setModel(list.getModel());  
         System.out.println(list.getModel());
         System.out.println(jList1.getModel());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Return = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        ProvideHelp = new javax.swing.JButton();
        NeedHelp = new javax.swing.JButton();
        Info = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(135, 176, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(522, 51));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Tutoring");

        Return.setBackground(new java.awt.Color(204, 204, 204));
        Return.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Return.setText("⬅");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Return, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jScrollPane1.setViewportView(jList1);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Pending help from EMIS Strudents:");

        ProvideHelp.setBackground(new java.awt.Color(204, 204, 204));
        ProvideHelp.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ProvideHelp.setText("Provide help");
        ProvideHelp.setPreferredSize(new java.awt.Dimension(165, 37));
        ProvideHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvideHelpActionPerformed(evt);
            }
        });

        NeedHelp.setBackground(new java.awt.Color(204, 204, 204));
        NeedHelp.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        NeedHelp.setText("Need Help?");
        NeedHelp.setPreferredSize(new java.awt.Dimension(78, 30));
        NeedHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeedHelpActionPerformed(evt);
            }
        });

        Info.setBackground(new java.awt.Color(204, 204, 204));
        Info.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Info.setText("Info");
        Info.setPreferredSize(new java.awt.Dimension(78, 30));
        Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProvideHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Info, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NeedHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProvideHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(NeedHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NeedHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeedHelpActionPerformed
        //Move to the "Tutoring2" GUI class:
        Tutoring2 x = new Tutoring2(UserName);
        this.hide();
        x.setVisible(true);
    }//GEN-LAST:event_NeedHelpActionPerformed

    private void ProvideHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvideHelpActionPerformed
        // TODO add your handling code here:
       if (!jList1.isSelectionEmpty()){ // Checks if a group has been selected before providing an error (z[0] null)
            String[] z = jList1.getSelectedValue().split(", ");
            String UserNamerecipient = z[0];
            ArrayList<String> EmailRecipient = controller.GetTutoringemail(z[0]);
            //Move to the "Tutoring3" GUI class:
            Tutoring3 x = new Tutoring3(UserName, UserNamerecipient, EmailRecipient.toString());
            this.hide();
            x.setVisible(true);
        }
        else{
           JOptionPane.showMessageDialog(null, "You first need to select a Help demand"); //Informing the user that he/she first has to select a Tutoring demand.
        }
        
        
    }//GEN-LAST:event_ProvideHelpActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        //Move to the "Menu" GUI class:
        Menu x = new Menu(UserName);
        this.hide();
        x.setVisible(true);
    }//GEN-LAST:event_ReturnActionPerformed

    private void InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoActionPerformed
        // TODO add your handling code here:
        if (!jList1.isSelectionEmpty()){ // Checks if a group has been selected before providing an error (z[0] null)
           String[] z = jList1.getSelectedValue().split(", ");
           JOptionPane.showMessageDialog(null, controller.GetAllTutoringInfo(z[0]));
        }
        else{
           JOptionPane.showMessageDialog(null, "You first need to select a Help demand"); //Informing the user that he/she first has to select a Tutoring demand.
        }
    }//GEN-LAST:event_InfoActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Info;
    private javax.swing.JButton NeedHelp;
    private javax.swing.JButton ProvideHelp;
    private javax.swing.JButton Return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
